---
title: "User_Study"
output: html_document
---


```{r importa_data}
library(readr)
annotations <- read_csv("annotations.csv")
View(annotations)
metadata <- read_csv("metadata.csv")
View(metadata)
```


#####################
   Get annotations  
#####################

```{r add_metadata}
instrument <- c(rep(metadata$instrument, 24))
annotations$instrument <- instrument
like <- c(rep(metadata$like, 24))
annotations$like <- like
```



######################
#  ROLE OF METADATA  #
######################

# Evaluate the role of matadata in listeners perception of Valence and Arousal. 

```{r multiple_regression_metadata}
library(MASS)
outcomes <- list(annotations$Valence, annotations$Arousal)
names <- c("valence", "arousal")
for (elem in seq_along(names)) {
  print(names[[elem]])
  m <- lm(outcomes[[elem]] ~ instrument + like, data=annotations)
  print(summary(m))
}
```

----------------------------------------------------------------------------------------------------------
Neither likeness nor musical background play a role in listeners perception of Arousal and Valence overall
----------------------------------------------------------------------------------------------------------


# Evaluate the role of matadata in listeners perception of Valence and Arousal within each song.

```{r multiple_regression_metada_song}
library(MASS)
categories <- as.list(unique(annotations$Song2))
for (i in seq_along(categories)) {
  selection <- annotations[which(annotations$Song2 %in% categories[[i]]),]
  outcomes <- list(selection$Valence, selection$Arousal)
  names <- c("valence", "arousal")
  for (elem in seq_along(names)) {
    m <- lm(outcomes[[elem]] ~ instrument + like, data=selection)
    res <- summary(m)$fstatistic
    p <- pf(res[1],res[2],res[3],lower.tail=F)
    attributes(p) <- NULL
    if (p < 0.05){
      print(names[[elem]])
      print(categories[[i]])
      print(summary(m))
    }
  }
}
```

```{r Bonferroni_adjustment}
adjusted_p_arousal <- p.adjust(0.0119, method = "bonferroni", n = 24)
adjusted_p_arousal
adjusted_p_valence <- p.adjust(0.0147, method = "bonferroni", n = 24)
adjusted_p_valence
```


----------------------------------------------------------------------------------------------------------
Neither likeness nor musical background play a role in listeners perception of Arousal and Valence overall
                        is confirmed for the withing song evaluation (as p > .2856)
----------------------------------------------------------------------------------------------------------



#################
#      V/A      #
#################

```{r ML_dimensions_all:data}
LM <- lm(Valence ~ Arousal, data=annotations)
summary(LM)
sqrt(0.07842)
plot(LM)

library(ggplot2)
ggplot(annotations, aes(x = Valence, y = Arousal)) +
  geom_smooth(method='lm') +
  geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

----------------------------------------------------------------------------------------------------------
    There is a positive relationship between both dimensions. Still, the correlation is low (r=0.28)
----------------------------------------------------------------------------------------------------------




#################
#    EMOTION    #
#################

```{r descriptive}
library(psych)
describeBy(annotations, group=annotations$Category)
```


```{r PLOTS_emo}
annotations[annotations == "TenderLonging"] <- "Tenderness"

lapply(annotations[, c("Category", "Arousal")], table)
ftable(xtabs(~ Category + Arousal, data = annotations))

library(ggplot2)
arousal.plot <- ggplot(annotations, aes(x = Arousal, y = Category)) +
  geom_boxplot(size = 1) +
  geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
arousal.plot
pdf("arousal.pdf", width=5, height=3)
print(arousal.plot)
dev.off()

lapply(annotations[, c("Category", "Valence")], table)
ftable(xtabs(~ Category + Valence, data = annotations))

valence.plot <- ggplot(annotations, aes(x = Valence, y = Category)) +
  geom_boxplot(size = 1, notch=FALSE) +   geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
valence.plot
pdf("valence.pdf", width=5, height=3)
print(valence.plot)
dev.off()
```


```{r barPlots}
library(ggpubr)
annotations[annotations == "TenderLonging"] <- "Tenderness"

counts <- table(annotations$Arousal, annotations$Category)
par(las=2) # make label text perpendicular to axis
par(mar=c(5,8,4,2)) # increase y-axis margin.
barplot(counts, main="Arousal ratings",
  xlab="Number of ratings", col=c("lightyellow", "yellow1", "orange1", "red", "red4"),
  legend = rownames(counts), horiz=TRUE, cex.names=1) 


counts <- table(annotations$Valence, annotations$Category)
par(las=2) # make label text perpendicular to axis
par(mar=c(5,8,4,2)) # increase y-axis margin.
barplot(counts, main="Valence ratings",
  xlab="Number of ratings", col=c("navy", "royalblue1", "paleturquoise1", "seagreen2", "chartreuse1"),
  legend = rownames(counts), horiz=TRUE, cex.names=1) 

```


```{r PLOT2_emo}
#annotations[annotations == "TenderLonging"] <- "Tenderness"
#sad <- annotations[which(annotations$Category == "Sadness"),]
#hist(sad$Valence)

lapply(annotations[, c("Category", "Arousal")], table)
ftable(xtabs(~ Category + Arousal, data = annotations))

library(ggplot2)
ggplot(annotations, aes(x = Arousal, y = Category))  +
  geom_boxplot(size = 1, width=0.5, length=0.5, notch=FALSE, outlier.size=0.5) +   #geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=12), axis.text.y = element_text(size=12, color="black"), axis.title.x = element_text(size=13, face="bold"),
  plot.margin = margin(1, 10, 1, 1, "cm"))

lapply(annotations[, c("Category", "Valence")], table)
ftable(xtabs(~ Category + Valence, data = annotations))

ggplot(annotations, aes(x = Valence, y = Category)) +
  geom_boxplot(size = 1, width=0.5, length=0.5, notch=FALSE, outlier.size=0.5, coef=0) +   #geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=12), axis.text.y = element_text(size=12, color="black"), axis.title.x = element_text(size=13, face="bold"),
  plot.margin = margin(1, 10, 1, 1, "cm"))
```


# Evaluation (per each perceived emotional category) whether there is a relationship between perceived Valence and Arousal.

```{r OLR_dimensions_each:song}
library(MASS)
categories <- list("Activation", "Amazement", "Dysphoria", "Sadness", "Joy", "Power", "Sensuality", "TenderLonging", "Tranquility", "Transcendence")
for (i in seq_along(categories)) {
  selection <- annotations[which(annotations$Category %in% categories[[i]]),]
  m <- lm(Valence ~ Arousal, data=selection)
  res <- summary(m)$fstatistic
  p <- pf(res[1],res[2],res[3],lower.tail=F)
  attributes(p) <- NULL
  if (p < 0.05){
    print(categories[[i]])
    print(summary(m))
  }
}
```


```{r Bonferroni_adjustment2}
adjusted_p_tender <- p.adjust(0.03458, method = "bonferroni", n = 10)
adjusted_p_tender
adjusted_p_sensuality <- p.adjust(0.00459, method = "bonferroni", n = 10)
adjusted_p_sensuality
adjusted_p_tranquility <- p.adjust(0.0018, method = "bonferroni", n = 10)
adjusted_p_tranquility
```



```{r ML_dimensions_positive:emotions}
positive_list <- c("Amazement", "Joy", "sensuality", "Tranquility")
positive_selection <- annotations[which(annotations$Category %in% positive_list),]
model.pos <- lm(Valence ~ Arousal, data=positive_selection)
summary(model.pos)
sqrt(0.23)
plot(model.pos)

library(ggplot2)
ggplot(positive_selection, aes(x = Valence, y = Arousal)) +
  geom_smooth(method='lm') +
  geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

----------------------------------------------------------------------------------------------------------
        For positive emotions there is a moderate positive relationship between both dimensions. 
                                   Pearson correlation coefficient (r=0.48)
----------------------------------------------------------------------------------------------------------


```{r ML_dimensions_positive:emotions}
negative_new_list <- c("Activation", "Dysphoria", "Sadness", "Power", "Transcendence", "TenderLonging")
negative_neu_selection <- annotations[which(annotations$Category %in% negative_new_list),]
model.neg <- lm(Valence ~ Arousal, data=negative_neu_selection)
summary(model.neg)
sqrt(0.07)
plot(model.neg)

library(ggplot2)
ggplot(negative_neu_selection, aes(x = Valence, y = Arousal)) +
  geom_smooth(method='lm') +
  geom_jitter(alpha = .5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

----------------------------------------------------------------------------------------------------------
      For negative/neutral emotions there is a low positive relationship between both dimensions. 
                              Pearson correlation coefficient (r=0.26)
----------------------------------------------------------------------------------------------------------

