---
title: "Features_Correlation"
output: html_document
---


```{r import_data}
library(readr)
library(janitor)
GS_data <- read_csv("GoldStandard.csv")
all_data <- read_csv("all_annotations.csv")
View(GS_data)
View(all_data)
```


```{r Correlations_mean_DIMENSIONvsFEATURE}
results.Arousal <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Valence <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())

for (dim in c("A_mean", "V_mean")){
  for (feature in colnames(GS_data)){
    if (feature != dim & feature != "Song" & feature != "Song2" & feature != "EWE_A" & feature != "EWE_V" & feature != "X1" & feature != "Category"){
      Pcor.val = cor(GS_data[,dim], GS_data[,feature], method="pearson")
      Scor.val = cor(GS_data[,dim], GS_data[,feature], method="spearman")
      Kcor.val = cor(GS_data[,dim], GS_data[,feature], method="kendall")
      new_row <- data.frame(feature, Pcor.val, Scor.val, Kcor.val)
      names(new_row) <- c("FEATURE", "PEARSON.cor", "SPEARMAN.cor", "KENDALL.cor")
      if (dim=="A_mean"){
        results.Arousal <- rbind(new_row, results.Arousal)
      }
      else{
        results.Valence <- rbind(new_row, results.Valence)
      }
    }
  }
}
results.Arousal <- results.Arousal[order(-abs(results.Arousal$PEARSON.cor)),]
results.Arousal
results.Valence <- results.Valence[order(-abs(results.Valence$PEARSON.cor)),]
results.Valence
```


```{r Correlations_EWE_DIMENSIONvsFEATURE}
results.Arousal <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Valence <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())

for (dim in c("EWE_A", "EWE_V")){
  for (feature in colnames(GS_data)){
    if (feature != dim & feature != "Song" & feature != "Song2" & feature != "A_mean" & feature != "V_mean" & feature != "X1" & feature != "Category"){
      Pcor.val = cor(GS_data[,dim], GS_data[,feature], method="pearson")
      Scor.val = cor(GS_data[,dim], GS_data[,feature], method="spearman")
      Kcor.val = cor(GS_data[,dim], GS_data[,feature], method="kendall")
      new_row <- data.frame(feature, Pcor.val, Scor.val, Kcor.val)
      names(new_row) <- c("FEATURE", "PEARSON.cor", "SPEARMAN.cor", "KENDALL.cor")
      if (dim=="EWE_A"){
        results.Arousal <- rbind(new_row, results.Arousal)
      }
      else{
        results.Valence <- rbind(new_row, results.Valence)
      }
    }
  }
}
results.Arousal <- results.Arousal[order(-abs(results.Arousal$PEARSON.cor)),]
results.Arousal
results.Valence <- results.Valence[order(-abs(results.Valence$PEARSON.cor)),]
results.Valence
```


```{r Correlations_EMOTIONvsFeatures}
library("dplyr")

results.Joy <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Dysphoria <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.TenderLonging <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Amazement <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Sadness <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Sensuality <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Tranquility <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Power <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Activation <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
results.Transcendence <- data.frame(FEATURE = character(), PEARSON.cor = numeric(), SPEARMAN.cor = numeric(), KENDALL.cor = numeric())
all_DFs <- list(results.Joy, results.Dysphoria, results.TenderLonging, results.Amazement, results.Sadness, results.Sensuality, results.Tranquility, results.Power, results.Activation, results.Transcendence)
all_DFs.emo <- c("Joy", "Dysphoria", "TenderLonging", "Amazement", "Sadness", "Sensuality", "Tranquility", "Power", "Activation", "Transcendence")

for (emo in all_DFs.emo){
  emo.df <- all_data
  emo.df$one.hot[emo.df$Category==emo] <- 1
  emo.df$one.hot[emo.df$Category!=emo] <- 0
  for (feature in colnames(subset(all_data, select=-c(row_index, X1, ID, Song, Category, Song2)))){
    vec <- pull(emo.df, feature)  # convert tibble to vector as it does not work for point biseral function
    #PB_corr = cor.test(emo.df$one.hot, emo.df[,feature], method="pearson")  #Point-Biserial Correlation
    PB_corr = cor.test(emo.df$one.hot, vec, method="pearson")  #Point-Biserial Correlation
    Pcor.val <- PB_corr$estimate
    Pcor.val
    names(Pcor.val) <- NULL  # Remove name
    Scor.val = cor(emo.df$one.hot, emo.df[,feature], method="spearman")
    Kcor.val = cor(emo.df$one.hot, emo.df[,feature], method="kendall")
    new_row <- data.frame(feature, Pcor.val, Scor.val, Kcor.val)
    names(new_row) <- c("FEATURE", "PEARSON.cor", "SPEARMAN.cor", "KENDALL.cor")
    index <- which(all_DFs.emo==emo)
    all_DFs[[index]] <- rbind(new_row, all_DFs[[index]])
  }
}

i = 0
for (df in all_DFs){
  i=i+1
  df2 <- df[order(-abs(df$PEARSON.cor)),]
  print(all_DFs.emo[[i]])
  print(df2)
}
```






